# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-27 03:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteAnuncio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=500, unique=True)),
                ('valor', models.FloatField()),
                ('fotos', models.FileField(blank=True, upload_to='fotos/%Y/%m/%d/')),
                ('videos', models.FileField(blank=True, upload_to='videos/%Y/%m/%d/')),
                ('auditoria', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Motel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=10)),
                ('fotos', models.FileField(blank=True, upload_to='fotos/%Y/%m/%d/')),
                ('descricao', models.CharField(max_length=200)),
                ('estrelas', models.IntegerField(choices=[(1, 'Uma'), (2, 'Duas'), (3, 'Tr\xeas'), (4, 'Quatro'), (5, 'Cinco')])),
                ('endereco', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=15)),
                ('bairro', models.CharField(max_length=25)),
                ('cidade', models.CharField(max_length=70)),
                ('estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AM', 'Amazonas'), ('AP', 'Amap\xe1'), ('BA', 'Bahia'), ('CE', 'Cear\xe1'), ('DF', 'Distrito Federal'), ('ES', 'Esp\xedrito Santo'), ('GO', 'Goi\xe1s'), ('MA', 'Maranh\xe3o'), ('MG', 'Minas Gerais'), ('MS', 'Mato Grosso do Sul'), ('MT', 'Mato Grosso'), ('PA', 'Par\xe1'), ('PB', 'Para\xedba'), ('PE', 'Pernambuco'), ('PI', 'Piau\xed'), ('PR', 'Paran\xe1'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RO', 'Rond\xf4nia'), ('RR', 'Roraima'), ('RS', 'Rio Grande do Sul'), ('SC', 'Santa Catarina'), ('SE', 'Sergipe'), ('SP', 'S\xe3o Paulo'), ('TO', 'Tocantins')], max_length=2)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quarto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotos', models.FileField(blank=True, upload_to='fotos/%Y/%m/%d/')),
                ('descricao', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=10)),
                ('preco', models.FloatField()),
                ('ocupado', models.BooleanField()),
                ('motel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_usuario.Motel')),
            ],
        ),
    ]
